Documentation:
   Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"
Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
LineLength:
   Max: 99
